### ISSUE TITLE
Spamming Error

### ISSUE THREAD

**Issue by MasterLuke117** [PetteriM1/WorldBorder#1]
```> 01:34:07 [FATAL] Could not pass event "cn.nukkit.event.player.PlayerTeleportEvent" to "WorldBorder v1.2": null on idk.plugin.worldborder.Main
> 01:34:07 [ERROR] Throwing
cn.nukkit.utils.EventException: null
at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34) ~[server.jar:?]
at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) ~[server.jar:?]
at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:546) [server.jar:?]
at cn.nukkit.Player.teleport(Player.java:4208) [server.jar:?]
at cn.nukkit.entity.Entity.teleport(Entity.java:2117) [server.jar:?]
at cn.yescallop.essentialsnk.command.defaults.home.HomeCommand.execute(HomeCommand.java:52) [EssentialsNK_1.8.0-2b2t.jar:?]
at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:257) [server.jar:?]
at cn.nukkit.Server.dispatchCommand(Server.java:753) [server.jar:?]
at com.boydti.fawe.nukkit.core.WorldEditListener.onPlayerCommandPreprocess(WorldEditListener.java:95) [FastAsyncWorldEdit-nukkit.jar:?]
at sun.reflect.GeneratedMethodAccessor141.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) [server.jar:?]
at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) [server.jar:?]
at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:546) [server.jar:?]
at cn.nukkit.Player.handleDataPacket(Player.java:2798) [server.jar:?]
at org.itxtech.synapseapi.SynapseEntry$Ticker.run(SynapseEntry.java:230) [SynapseAPI-PM1E-X%20(4).jar:?]
at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99) [server.jar:?]
at cn.nukkit.scheduler.ServerScheduler.runTasks(ServerScheduler.java:296) [server.jar:?]
at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:277) [server.jar:?]
at cn.nukkit.Server.tick(Server.java:1134) [server.jar:?]
at cn.nukkit.Server.tickProcessor(Server.java:905) [server.jar:?]
at cn.nukkit.Server.start(Server.java:882) [server.jar:?]
at cn.nukkit.Server.<init>(Server.java:567) [server.jar:?]
at cn.nukkit.Nukkit.main(Nukkit.java:112) [server.jar:?]
Caused by: java.lang.NullPointerException
at idk.plugin.worldborder.Main.onTeleport(Main.java:53) ~[?:?]
at sun.reflect.GeneratedMethodAccessor144.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) ~[server.jar:?]
... 24 more```

**Comment by PetteriM1** [comment]
Hmm looks like something is setting the teleport target/target level to null
